---
title: "Uncertainty analysis with ERA5 (Water volume)"
execute: 
  echo: false
  fig-width: 10
  fig-height: 7
format: 
  revealjs:
    self-contained: true
    
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(stars)

sf_use_s2(F)

dir_data <- "/mnt/pers_disk/dif_era_cordex/dif"

source(here::here("scripts_v4", "0_output_vars.R")) 

land_pol <- 
  "/mnt/bucket_mine/misc_data/physical/ne_110m_land/" |> 
  st_read(quiet = T)

land_df <- 
  land_pol %>% 
  st_coordinates %>% 
  as_tibble %>% 
  mutate(L = paste0(L1, "_", L2))



fn_plot <- function(stars_obj, revv, tit, subtit, dif_type){
  
  # stars_obj = s
  # revv = r
  # tit = d
  # subtit = dd

  
  stars_obj <- suppressMessages(stars_obj[land_pol])
  
  tb <- 
    stars_obj |>
    units::drop_units() |> 
    merge(name = "stats") |> 
    setNames("value") |> 
    as_tibble()
  
  
  if (dif_type == "abs"){
    
    un <- 
      stars_obj |> 
      pull() |> 
      units::deparse_unit()


  
    lim <- max(abs(quantile(tb$value, c(0.05, 0.95), na.rm = T)))

    p_nonlog <- 
      ggplot() +
      geom_raster(data = tb, aes(lon, lat, fill = value)) + 
      geom_path(data = land_df, aes(X, Y, group = L), linewidth = 0.25) +
      facet_wrap(~stats, ncol = 2,dir = "v") +
      coord_cartesian(ylim = c(-55, 75), xlim = c(-155, 160)) +
      theme(axis.title = element_blank(),
            legend.position = "bottom") +
      labs(title = tit,
          subtitle = subtit) +
      colorspace::scale_fill_binned_diverging(na.value = "transparent",
                                              n.breaks = 9,
                                              guide = guide_colorsteps(barheight = 0.5,
                                                                      barwidth = 24,
                                                                      title.position = "left"),
                                              name = un,
                                              limits = c(-lim, lim),
                                              oob = scales::squish,
                                              rev = revv)


    # **********

    # n <- 4

    tb_trans <- 
        tb |> 
        mutate(value_trans = if_else(value == 0, 0, log(abs(value))),
              #  value_trans = (abs(value))^(1/n),
              value_trans = if_else(value < 0, value_trans*-1, value_trans))

    lim <- max(abs(quantile(tb_trans$value_trans, c(0.05, 0.95), na.rm = T))) |> round()
    br <- seq(-lim, lim, length.out = 11)
    lab <- exp(abs(br))
    # lab <- br^n
    lab[br < 0] <- lab[br < 0]*-1
    lab[br == 0] <- 0
    lab <- round(lab)

    p_log <- 
      ggplot() +
      geom_raster(data = tb_trans, aes(lon, lat, fill = value_trans)) + 
      geom_path(data = land_df, aes(X, Y, group = L), linewidth = 0.25) +
      facet_wrap(~stats, ncol = 2,dir = "v") +
      coord_cartesian(ylim = c(-55, 75), xlim = c(-155, 160)) +
      theme(axis.title = element_blank(),
            legend.position = "bottom") +
      labs(title = tit,
          subtitle = subtit) +
      colorspace::scale_fill_binned_diverging(na.value = "transparent",
                                              guide = guide_colorsteps(barheight = 0.5,
                                                                      barwidth = 30,
                                                                      title.position = "left"),
                                              name = str_glue("{un}    "),
                                              breaks = br,
                                              labels = lab,
                                              limits = c(-lim, lim),
                                              oob = scales::squish,
                                              rev = revv)

    list(p_nonlog, p_log)

    
  } else {
    
    if (any(tb$value == 0, na.rm = T)) {
      tb <- 
        tb |> 
        mutate(value = if_else(value == 0, NA, value))
    }


    tb_log <- 
      tb |> 
      mutate(value = log(value))
    
    limss <- quantile(tb_log$value, c(0.05, 0.95), na.rm = T) |> round(1)
    
    ggplot() +
      geom_raster(data = tb_log, aes(lon, lat, fill = value)) + 
      geom_path(data = land_df, aes(X, Y, group = L), linewidth = 0.25) +
      facet_wrap(~stats, ncol = 2,dir = "v") +
      coord_cartesian(ylim = c(-55, 75), xlim = c(-155, 160)) +
      theme(axis.title = element_blank(),
            legend.position = "bottom") +
      labs(title = tit,
           subtitle = subtit) +
      colorspace::scale_fill_binned_diverging(na.value = "transparent",
                                              # n.breaks = 9,
                                              guide = guide_colorsteps(barheight = 0.5,
                                                                       barwidth = 24,
                                                                       title.position = "left"),
                                              name = "X   ",
                                              breaks = seq(first(limss), last(limss), 0.2),
                                              labels = exp(seq(first(limss), last(limss), 0.2)) |> round(1),
                                              limits = c(first(limss), last(limss)),
                                              oob = scales::squish,
                                              rev = revv)
    
  }
  
}






fn_main <- function(nm, abs = T, revv = F, wl = NA, loggg = F) {
  
  # nm <- output_vars[22]
  # # delta = T no more delta
  # abs = F
  # revv = T
  # wl = 1
  
  
  if(abs){
    dif_type = "abs"
  } else {
    dif_type = "rel"
  }
  
  
  f <- str_glue("{dir_data}/era-cordex-dif_{dif_type}_{str_replace_all(nm, '_', '-')}.nc")
  
  s <- 
    read_ncdf(f) |> 
    suppressMessages()
  
  s <- 
    s |> 
    slice(wl, wl)
  
  if(dif_type == "abs"){
    
    d <- str_glue("Absolute difference: CORDEX - ERA5 [{c('0.5° WL', '1.0° WL')[wl]}]")
    
  } else {
    
    d <- str_glue("Relative difference: CORDEX / ERA5 [{c('0.5° WL', '1.0° WL')[wl]}]")
    
  }
  
  
  dd <- 
    nm |> 
    str_replace_all("_", " ") |>  
    str_replace_all("-", " ") |>
    str_to_sentence()
  
  if (!revv) {
    r <- F
  } else {
    r <- T
  }

  fn_plot(s, r, d, dd, dif_type)
   
  
}


```


- Maps show CORDEX vs. ERA differences
  - Red (blue) means CORDEX runs drier (wetter) than ERA5
- Four difference maps per variable: 
  - Two warming levels (0.5° and  1.0°)...
  - ...absolute and relative differences for each.


---

```{r}

p <- fn_main(output_vars[20], wl = 1, revv = T, abs = T) # 3
p[[1]]

```

---

```{r}

p[[2]]

```

---

```{r}

fn_main(output_vars[20], wl = 1, revv = T, abs = F) # 4

```

---

```{r}

p <- fn_main(output_vars[20], wl = 2, revv = T, abs = T) # 5
p[[1]]

```

---

```{r}

p[[2]]

```

---

```{r}

fn_main(output_vars[20], wl = 2, revv = T, abs = F) # 6

```

---

```{r}

p <- fn_main(output_vars[21], wl = 1, revv = T, abs = T) # 7
p[[1]]

```

---

```{r}

p[[2]]

```

---

```{r}

fn_main(output_vars[21], wl = 1, revv = T, abs = F) # 8

```

---

```{r}

p <- fn_main(output_vars[21], wl = 2, revv = T, abs = T) # 9
p[[1]]

```

---

```{r}

p[[2]]

```

---

```{r}

fn_main(output_vars[21], wl = 2, revv = T, abs = F) # 10

```

---

```{r}

p <- fn_main(output_vars[22], wl = 1, revv = T, abs = T) # 11
p[[1]]

```

---

```{r}

p[[2]]

```

---

```{r}

fn_main(output_vars[22], wl = 1, revv = T, abs = F) # 12

```

---

```{r}

p <- fn_main(output_vars[22], wl = 2, revv = T, abs = T) # 13
p[[1]]

```

---

```{r}

p[[2]]

```

---

```{r}

fn_main(output_vars[22], wl = 2, revv = T, abs = F) # 14

```

---

```{r}

p <- fn_main(output_vars[23], wl = 1, revv = T, abs = T) # 15
p[[1]]

```

---

```{r}

p[[2]]

```

---

```{r}

fn_main(output_vars[23], wl = 1, revv = T, abs = F) # 16

```

---

```{r}

p <- fn_main(output_vars[23], wl = 2, revv = T, abs = T) # 17
p[[1]]

```

---

```{r}

p[[2]]

```

---

```{r}

fn_main(output_vars[23], wl = 2, revv = T, abs = F) # 18

```

---

```{r}

wd_cordex <- 
  str_glue("{dir_data}/wd_cordex.nc") |> 
  read_ncdf() |> 
  suppressMessages() |> 
  units::drop_units()

wd_cordex <- suppressMessages(wd_cordex[land_pol])

tb_cordex <- 
  wd_cordex |> 
  merge(name = "stats") |> 
  setNames("d") |> 
  as_tibble() |> 
  mutate(wl = wl + 0.5) |> 
  mutate(d = log(d))

tb_cordex_wl <- 
  tb_cordex |> 
  filter(wl == 0.5) |> 
  filter(stats != "perc_100")

lim <- quantile(tb_cordex_wl$d, c(0.05, 0.95), na.rm = T) |> round()
br <- seq(first(lim), last(lim), length.out = 11)
lb <- round(exp(br))

ggplot() +
  geom_raster(data = tb_cordex_wl, aes(lon, lat, fill = d)) + 
  geom_path(data = land_df, aes(X, Y, group = L), linewidth = 0.25) +
  facet_wrap(~stats, ncol = 2,dir = "v") +
  coord_cartesian(ylim = c(-55, 75), xlim = c(-155, 160)) +
  theme(axis.title = element_blank(),
        legend.position = "bottom") +
  labs(title = "Levels: CORDEX [0.5°C]",
      subtitle = "Wettest day") +
  colorspace::scale_fill_binned_sequential("plasma",
                                          na.value = "transparent",
                                          n.breaks = 9,
                                          guide = guide_colorsteps(barheight = 0.5,
                                                                  barwidth = 24,
                                                                    title.position ="left"),
                                          name = "mm   ",
                                          breaks = br,
                                          labels = lb,
                                          limits = c(lim[1], lim[2]),
                                          oob = scales::squish,
                                          rev = F)


```

---

```{r}

wd_era <- 
  str_glue("{dir_data}/wd_era.nc") |> 
  read_ncdf() |> 
  suppressMessages() |> 
  units::drop_units()

wd_era <- suppressMessages(wd_era[land_pol])

tb_era <- 
  wd_era |> 
  merge(name = "stats") |> 
  setNames("d") |> 
  as_tibble() |> 
  mutate(wl = wl + 0.5) |> 
  mutate(d = log(d))

tb_era_wl <- 
  tb_era |> 
  filter(wl == 0.5) |> 
  filter(stats != "perc_100")

lim <- quantile(tb_era_wl$d, c(0.05, 0.95), na.rm = T) |> round()
br <- seq(first(lim), last(lim), length.out = 11)
lb <- round(exp(br))

ggplot() +
  geom_raster(data = tb_era_wl, aes(lon, lat, fill = d)) + 
  geom_path(data = land_df, aes(X, Y, group = L), linewidth = 0.25) +
  facet_wrap(~stats, ncol = 2,dir = "v") +
  coord_cartesian(ylim = c(-55, 75), xlim = c(-155, 160)) +
  theme(axis.title = element_blank(),
        legend.position = "bottom") +
  labs(title = "Levels: ERA [0.5°C]",
      subtitle = "Wettest day") +
  colorspace::scale_fill_binned_sequential("plasma",
                                          na.value = "transparent",
                                          n.breaks = 9,
                                          guide = guide_colorsteps(barheight = 0.5,
                                                                  barwidth = 24,
                                                                    title.position ="left"),
                                          name = "mm   ",
                                          breaks = br,
                                          labels = lb,
                                          limits = c(lim[1], lim[2]),
                                          oob = scales::squish,
                                          rev = F)

```

---

```{r}

tb_cordex_wl <- 
  tb_cordex |> 
  filter(wl == 1.0) |> 
  filter(stats != "perc_100")

lim <- quantile(tb_cordex_wl$d, c(0.05, 0.95), na.rm = T) |> round()
br <- seq(first(lim), last(lim), length.out = 11)
lb <- round(exp(br))

ggplot() +
  geom_raster(data = tb_cordex_wl, aes(lon, lat, fill = d)) + 
  geom_path(data = land_df, aes(X, Y, group = L), linewidth = 0.25) +
  facet_wrap(~stats, ncol = 2,dir = "v") +
  coord_cartesian(ylim = c(-55, 75), xlim = c(-155, 160)) +
  theme(axis.title = element_blank(),
        legend.position = "bottom") +
  labs(title = "Levels: CORDEX [1.0°C]",
      subtitle = "Wettest day") +
  colorspace::scale_fill_binned_sequential("plasma",
                                          na.value = "transparent",
                                          n.breaks = 9,
                                          guide = guide_colorsteps(barheight = 0.5,
                                                                  barwidth = 24,
                                                                    title.position ="left"),
                                          name = "mm   ",
                                          breaks = br,
                                          labels = lb,
                                          limits = c(lim[1], lim[2]),
                                          oob = scales::squish,
                                          rev = F)

```

---

```{r}

tb_era_wl <- 
  tb_era |> 
  filter(wl == 1.0) |> 
  filter(stats != "perc_100")

lim <- quantile(tb_era_wl$d, c(0.05, 0.95), na.rm = T) |> round()
br <- seq(first(lim), last(lim), length.out = 11)
lb <- round(exp(br))

ggplot() +
  geom_raster(data = tb_era_wl, aes(lon, lat, fill = d)) + 
  geom_path(data = land_df, aes(X, Y, group = L), linewidth = 0.25) +
  facet_wrap(~stats, ncol = 2,dir = "v") +
  coord_cartesian(ylim = c(-55, 75), xlim = c(-155, 160)) +
  theme(axis.title = element_blank(),
        legend.position = "bottom") +
  labs(title = "Levels: ERA [1.0°C]",
      subtitle = "Wettest day") +
  colorspace::scale_fill_binned_sequential("plasma",
                                          na.value = "transparent",
                                          n.breaks = 9,
                                          guide = guide_colorsteps(barheight = 0.5,
                                                                  barwidth = 24,
                                                                    title.position ="left"),
                                          name = "mm   ",
                                          breaks = br,
                                          labels = lb,
                                          limits = c(lim[1], lim[2]),
                                          oob = scales::squish,
                                          rev = F)

```

---

```{r}

p <- fn_main(output_vars[24], wl = 1, revv = T, abs = T) # 19
p[[1]]

```

---

```{r}

p[[2]]

```

---

```{r}

fn_main(output_vars[24], wl = 1, revv = T, abs = F) # 20

```

---

```{r}

p <- fn_main(output_vars[24], wl = 2, revv = T, abs = T) # 21
p[[1]]

```

---

```{r}

p[[2]]

```

---

```{r}

fn_main(output_vars[24], wl = 2, revv = T, abs = F) # 22

```

---

```{r}

tb_cordex_wl <- 
  tb_cordex |> 
  filter(wl == 0.5) |> 
  filter(stats == "perc_100")

lim <- quantile(tb_cordex_wl$d, c(0.05, 0.95), na.rm = T) |> round()
br <- seq(first(lim), last(lim), length.out = 11)
lb <- round(exp(br))

ggplot() +
  geom_raster(data = tb_cordex_wl, aes(lon, lat, fill = d)) + 
  geom_path(data = land_df, aes(X, Y, group = L), linewidth = 0.25) +
  # facet_wrap(~stats, ncol = 2,dir = "v") +
  coord_cartesian(ylim = c(-55, 75), xlim = c(-155, 160)) +
  theme(axis.title = element_blank(),
        legend.position = "bottom") +
  labs(title = "Levels: CORDEX [0.5°C]",
      subtitle = "Max wettest day") +
  colorspace::scale_fill_binned_sequential("plasma",
                                          na.value = "transparent",
                                          n.breaks = 9,
                                          guide = guide_colorsteps(barheight = 0.5,
                                                                  barwidth = 24,
                                                                    title.position ="left"),
                                          name = "mm   ",
                                          breaks = br,
                                          labels = lb,
                                          limits = c(lim[1], lim[2]),
                                          oob = scales::squish,
                                          rev = F)

```

---

```{r}

tb_era_wl <- 
  tb_era |> 
  filter(wl == 0.5) |> 
  filter(stats == "perc_100")

lim <- quantile(tb_era_wl$d, c(0.05, 0.95), na.rm = T) |> round()
br <- seq(first(lim), last(lim), length.out = 11)
lb <- round(exp(br))

ggplot() +
  geom_raster(data = tb_era_wl, aes(lon, lat, fill = d)) + 
  geom_path(data = land_df, aes(X, Y, group = L), linewidth = 0.25) +
  # facet_wrap(~stats, ncol = 2,dir = "v") +
  coord_cartesian(ylim = c(-55, 75), xlim = c(-155, 160)) +
  theme(axis.title = element_blank(),
        legend.position = "bottom") +
  labs(title = "Levels: ERA [0.5°C]",
      subtitle = "Max wettest day") +
  colorspace::scale_fill_binned_sequential("plasma",
                                          na.value = "transparent",
                                          n.breaks = 9,
                                          guide = guide_colorsteps(barheight = 0.5,
                                                                  barwidth = 24,
                                                                    title.position ="left"),
                                          name = "mm   ",
                                          breaks = br,
                                          labels = lb,
                                          limits = c(lim[1], lim[2]),
                                          oob = scales::squish,
                                          rev = F)
```

---

```{r}

tb_cordex_wl <- 
  tb_cordex |> 
  filter(wl == 1.0) |> 
  filter(stats == "perc_100")

lim <- quantile(tb_cordex_wl$d, c(0.05, 0.95), na.rm = T) |> round()
br <- seq(first(lim), last(lim), length.out = 11)
lb <- round(exp(br))

ggplot() +
  geom_raster(data = tb_cordex_wl, aes(lon, lat, fill = d)) + 
  geom_path(data = land_df, aes(X, Y, group = L), linewidth = 0.25) +
  # facet_wrap(~stats, ncol = 2,dir = "v") +
  coord_cartesian(ylim = c(-55, 75), xlim = c(-155, 160)) +
  theme(axis.title = element_blank(),
        legend.position = "bottom") +
  labs(title = "Levels: CORDEX [1.0°C]",
      subtitle = "Max wettest day") +
  colorspace::scale_fill_binned_sequential("plasma",
                                          na.value = "transparent",
                                          n.breaks = 9,
                                          guide = guide_colorsteps(barheight = 0.5,
                                                                  barwidth = 24,
                                                                    title.position ="left"),
                                          name = "mm   ",
                                          breaks = br,
                                          labels = lb,
                                          limits = c(lim[1], lim[2]),
                                          oob = scales::squish,
                                          rev = F)

```

---

```{r}

tb_era_wl <- 
  tb_era |> 
  filter(wl == 1.0) |> 
  filter(stats == "perc_100")

lim <- quantile(tb_era_wl$d, c(0.05, 0.95), na.rm = T) |> round()
br <- seq(first(lim), last(lim), length.out = 11)
lb <- round(exp(br))

ggplot() +
  geom_raster(data = tb_era_wl, aes(lon, lat, fill = d)) + 
  geom_path(data = land_df, aes(X, Y, group = L), linewidth = 0.25) +
  # facet_wrap(~stats, ncol = 2,dir = "v") +
  coord_cartesian(ylim = c(-55, 75), xlim = c(-155, 160)) +
  theme(axis.title = element_blank(),
        legend.position = "bottom") +
  labs(title = "Levels: ERA [1.0°C]",
      subtitle = "Max wettest day") +
  colorspace::scale_fill_binned_sequential("plasma",
                                          na.value = "transparent",
                                          n.breaks = 9,
                                          guide = guide_colorsteps(barheight = 0.5,
                                                                  barwidth = 24,
                                                                    title.position ="left"),
                                          name = "mm   ",
                                          breaks = br,
                                          labels = lb,
                                          limits = c(lim[1], lim[2]),
                                          oob = scales::squish,
                                          rev = F)
```

---

```{r}

p <- fn_main("max-wettest-day", wl = 1, revv = T, abs = T) # 23
p[[1]]

```

---

```{r}

p[[2]]

```

---

```{r}

fn_main("max-wettest-day", wl = 1, revv = T, abs = F) # 24

```

---

```{r}

p <- fn_main("max-wettest-day", wl = 2, revv = T, abs = T) # 25
p[[1]]

```

---

```{r}

p[[2]]

```

---

```{r}

fn_main("max-wettest-day", wl = 2, revv = T, abs = F) # 26

```

---



